Task/Models/Matrix.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Task.DataAnnotation;

namespace Task.Models
{
   
    public class Matrix
    {
       
        [Required]
        [Range(0, 10)]
        public int X { get ;  set ;  }
        public int Y { get ;  set;  }

        public int[,] mas;
       
        [Range(0, 10)]
       
        public int Height{ get; set; }
        [Required]
        
        [Range(0, 10)]
        public int Width { get; set; }
    }
}

Task/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task/Controllers/MatrixController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class MatrixController : Controller
    {
        // GET: Coordinate
        public ActionResult Index()
        {
            return View("CreateMatrix");
        }

        // GET: Coordinate/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Coordinate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coordinate/Create
        [HttpPost]
        public ActionResult Create(Matrix matrix)
        {
            if (matrix.X > matrix.Width || matrix.Y > matrix.Height)
            {
                ViewBag.Error= "The size of Matrix not mathes assigning the coordinates";
                return View("CreateMatrix");
            };
            matrix.mas = new int[matrix.Height, matrix.Width];
            for (int i = 0; i < matrix.mas.GetLength(0); i++)
                for (int j = 0; j < matrix.mas.GetLength(1); j++)
                    matrix.mas[i, j] = -1;

            matrix.mas = Fill(matrix.mas, matrix.X, matrix.Y, 0);
                ViewBag.Matrix = matrix.mas;
                ViewBag.X = matrix.X;
                ViewBag.Y = matrix.Y;
                return View("Result");
        }
        int[,] Fill(int[,] mas, int X, int Y, int step)
        {
            int Weig = mas.GetLength(0), Heigh = mas.GetLength(1);
            for (int i = 0; i < Weig; i++)
                for (int j = 0; j < Heigh; j++)
                {
                    if (X + i < Weig && Y + j < Heigh)
                        mas[X + i, Y + j] = i + j;
                    if (X + i < Weig && Y - j >= 0)
                        mas[X + i, Y - j] = i + j;
                    if (X - i >= 0 && Y + j < Heigh)
                        mas[X - i, Y + j] = i + j;
                    if (X - i >= 0 && Y - j >= 0)
                        mas[X - i, Y - j] = i + j;
                }
            return mas;
        }
        // GET: Coordinate/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Coordinate/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: Coordinate/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Coordinate/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Task/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Task/Views/Matrix/CreateMatrix.cshtml
@model Task.Models.Matrix
	 

@{
    ViewBag.Title = "Coordinate";
}

<h2>Coordinate</h2>


@using (Html.BeginForm("Create", "Matrix"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
	<h4>Fill the Coordinates</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.X, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.X, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.X, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Y, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Y, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Y, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })

			@Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
		</div>
	</div>
	 @Html.Label((string)ViewBag.Error ?? "", new { @class = "text-danger" })
	<div class="col-md-offset-2 col-md-10">
		<input type="submit" value="Create" class="btn btn-default" />
	</div>
</div>
}
<div>
    @Html.ActionLink("Back to the Home", "_Layout")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Task/Views/Matrix/Result.cshtml
@model Task.Models.Matrix

@{
	ViewBag.Title = "Result";
}

<h2>Result</h2>

<table>
	@{
		int[,] matrix = ViewBag.Matrix;
		for (int i = 0; i < matrix.GetLength(0); i++)
		{
			<tr>
				@for (int j = 0; j < matrix.GetLength(1); j++)
				{
			if (int.Parse(ViewBag.X.ToString()) == i && int.Parse(ViewBag.Y.ToString()) == j)
			{
			<td style="width:100px;background-color:red;height:50px;font-size:16px">@matrix[i, j]</td>}
			else
			{
						<td style="width:100px;background-color:yellowgreen;height:50px;font-size:16px">@matrix[i, j]</td>}
		    }
			</tr>
		}
	}


</table>

Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application-Wave</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Create Matrix","Index","Matrix")</li>
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>